/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loteria;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author itel
 */
public class Loteria extends javax.swing.JFrame
{

    private List<String> numSorteados = new ArrayList<String>();

    List<String[]> numJogados = new ArrayList<String[]>();

    /**
     * Creates new form Loteria
     */
    public Loteria()
    {
        initComponents();
        progress.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        painel = new javax.swing.JPanel();
        logotipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelNumeros = new javax.swing.JPanel();
        n1 = new javax.swing.JComboBox();
        n2 = new javax.swing.JComboBox();
        n3 = new javax.swing.JComboBox();
        n4 = new javax.swing.JComboBox();
        n5 = new javax.swing.JComboBox();
        n6 = new javax.swing.JComboBox();
        n7 = new javax.swing.JComboBox();
        n8 = new javax.swing.JComboBox();
        n9 = new javax.swing.JComboBox();
        n10 = new javax.swing.JComboBox();
        n11 = new javax.swing.JComboBox();
        n12 = new javax.swing.JComboBox();
        n13 = new javax.swing.JComboBox();
        n14 = new javax.swing.JComboBox();
        n15 = new javax.swing.JComboBox();
        buttonVisualizar = new javax.swing.JButton();
        buttonConferir = new javax.swing.JButton();
        progress = new javax.swing.JProgressBar();
        buttonMaisJogados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lotofácil");
        setResizable(false);

        logotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lotofacil.png"))); // NOI18N

        jLabel1.setText("Selecione abaixos os números sorteados do concurso a ser");

        jLabel2.setText("conferido:");

        n1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        n15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        javax.swing.GroupLayout painelNumerosLayout = new javax.swing.GroupLayout(painelNumeros);
        painelNumeros.setLayout(painelNumerosLayout);
        painelNumerosLayout.setHorizontalGroup(
            painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNumerosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelNumerosLayout.createSequentialGroup()
                        .addComponent(n11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelNumerosLayout.createSequentialGroup()
                        .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelNumerosLayout.createSequentialGroup()
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelNumerosLayout.setVerticalGroup(
            painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonVisualizar.setText("Visualizar Jogos");
        buttonVisualizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonVisualizarActionPerformed(evt);
            }
        });

        buttonConferir.setText("Conferir Resultados");
        buttonConferir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonConferirActionPerformed(evt);
            }
        });

        buttonMaisJogados.setText("Mais Jogados");
        buttonMaisJogados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonMaisJogadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(painelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(buttonVisualizar)
                        .addGap(18, 18, 18)
                        .addComponent(buttonMaisJogados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonConferir))
                    .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logotipo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(painelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVisualizar)
                    .addComponent(buttonConferir)
                    .addComponent(buttonMaisJogados))
                .addGap(18, 18, 18)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVisualizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonVisualizarActionPerformed
    {//GEN-HEADEREND:event_buttonVisualizarActionPerformed
        try
        {
            JOptionPane.showMessageDialog(null, visualizarJogos(), "Lista de Jogos", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(Loteria.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex)
        {
            Logger.getLogger(Loteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonVisualizarActionPerformed

    private void buttonConferirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonConferirActionPerformed
    {//GEN-HEADEREND:event_buttonConferirActionPerformed
        SwingWorker worker = new SwingWorker()
        {
            @Override
            protected Object doInBackground() throws Exception
            {
                progress.setVisible(true);
                progress.setIndeterminate(true);
                exibirResultado();
                progress.setVisible(false);
                return null;
            }

            @Override
            protected void done()
            {
                //barra.setVisible(false);
            }
        };
        worker.execute();
    }//GEN-LAST:event_buttonConferirActionPerformed

    private void buttonMaisJogadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonMaisJogadosActionPerformed
    {//GEN-HEADEREND:event_buttonMaisJogadosActionPerformed
        try
        {
            String resultado = verificarMaisJogados();
            resultado = resultado.substring(4);
            JOptionPane.showMessageDialog(null, resultado, "Seus Números mais Jogados!", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(Loteria.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex)
        {
            Logger.getLogger(Loteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMaisJogadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Loteria().setVisible(true);
            }
        });
    }

    private String verificarMaisJogados() throws FileNotFoundException, IOException
    {
        String maisJogados = null;
        String linha = null;
        int resultado[] = new int[26];

        for (int i = 0; i < resultado.length; i++)
        {
            resultado[i] = 0;
        }
        BufferedReader leitor = lerArquivo();
        while ((linha = leitor.readLine()) != null)
        {
            String[] numeros = linha.split(",");
            for (int i = 0; i < numeros.length; i++)
            {
                int numero = Integer.valueOf(numeros[i]);
                resultado[numero] = resultado[numero] + 1;
            }

        }

        for (int i = 1; i < resultado.length; i++)
        {
            maisJogados = maisJogados + i + " = " + resultado[i] + " Vezes\n";
        }
        return maisJogados;
    }

    private void exibirResultado() throws FileNotFoundException, IOException
    {
        numSorteados.clear();
        if (validarCampos() == true)
        {
            if (validarNumerosRepetidos() == true)
            {
                numJogados.clear();
                carregarJogos();
                String resultado = conferirResultados();
                resultado = resultado.substring(4);
                gravarArquivo(resultado);
                System.out.println("\n\n");
                System.out.println(resultado);
                JOptionPane.showMessageDialog(null, "Os Jogos foram conferidos e foi criado o arquivo resultado.txt contendo os resultados.", "Jogos Conferidos com Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Favor selecionar Números distintos", "Existem Números Repetidos", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Favor selecionar todos o Números", "Favor selecionar todos o Números", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void gravarArquivo(String conteudo) throws FileNotFoundException, IOException
    {
        File arquivo;
        arquivo = new File("resultado.txt");
        FileOutputStream fos = new FileOutputStream(arquivo);
        fos.write(conteudo.getBytes());
    }

    private String conferirResultados()
    {
        String resultado = null;
        int numJogo = 1;
        int acertos = 0;
        for (String[] n : numJogados)
        {
            for (int i = 0; i < n.length; i++)
            {
                int x = Integer.valueOf(n[i]);
                for (String sorteado : numSorteados)
                {
                    int y = Integer.valueOf(sorteado);
                    if (x == y)
                    {
                        acertos++;
                    }
                }
            }
            System.out.println("Jogo " + numJogo + ": " + n[0] + "," + n[1] + "," + n[2] + "," + n[3] + "," + n[4] + ","
                               + n[5] + "," + n[6] + "," + n[7] + "," + n[8] + "," + n[9] + ","
                               + n[10] + "," + n[11] + "," + n[12] + "," + n[13] + "," + n[14]
                               + " - Acertos: " + acertos);
            resultado = resultado + "Jogo " + numJogo + ": " + n[0] + "," + n[1] + "," + n[2] + "," + n[3] + "," + n[4] + ","
                        + n[5] + "," + n[6] + "," + n[7] + "," + n[8] + "," + n[9] + ","
                        + n[10] + "," + n[11] + "," + n[12] + "," + n[13] + "," + n[14]
                        + " - Acertos: " + acertos + "\n";
            numJogo++;
            acertos = 0;
        }
        return resultado;
    }

    private void carregarJogos() throws FileNotFoundException, IOException
    {
        String linha = null;
        BufferedReader leitor = lerArquivo();
        while ((linha = leitor.readLine()) != null)
        {
            String[] jogo = linha.split(",");
            numJogados.add(jogo);
        }
    }

    private boolean validarNumerosRepetidos()
    {
        for (int i = 0; i < numSorteados.size(); i++)
        {
            int n = Integer.valueOf(numSorteados.get(i));
            for (int j = i + 1; j < numSorteados.size(); j++)
            {
                if (n == Integer.valueOf(numSorteados.get(j)))
                {
                    return false;
                }
            }
        }
        return true;
    }

    private boolean validarCampos()
    {
        String num1 = n1.getSelectedItem().toString();
        String num2 = n2.getSelectedItem().toString();
        String num3 = n3.getSelectedItem().toString();
        String num4 = n4.getSelectedItem().toString();
        String num5 = n5.getSelectedItem().toString();
        String num6 = n6.getSelectedItem().toString();
        String num7 = n7.getSelectedItem().toString();
        String num8 = n8.getSelectedItem().toString();
        String num9 = n9.getSelectedItem().toString();
        String num10 = n10.getSelectedItem().toString();
        String num11 = n11.getSelectedItem().toString();
        String num12 = n12.getSelectedItem().toString();
        String num13 = n13.getSelectedItem().toString();
        String num14 = n14.getSelectedItem().toString();
        String num15 = n15.getSelectedItem().toString();

        if (num1.isEmpty() || num2.isEmpty() || num3.isEmpty() || num4.isEmpty() || num5.isEmpty()
            || num6.isEmpty() || num7.isEmpty() || num8.isEmpty() || num9.isEmpty() || num10.isEmpty()
            || num11.isEmpty() || num12.isEmpty() || num13.isEmpty() || num14.isEmpty() || num15.isEmpty())
        {
            return false;
        }
        else
        {
            numSorteados.add(num1);
            numSorteados.add(num2);
            numSorteados.add(num3);
            numSorteados.add(num4);
            numSorteados.add(num5);
            numSorteados.add(num6);
            numSorteados.add(num7);
            numSorteados.add(num8);
            numSorteados.add(num9);
            numSorteados.add(num10);
            numSorteados.add(num11);
            numSorteados.add(num12);
            numSorteados.add(num13);
            numSorteados.add(num14);
            numSorteados.add(num15);
            return true;
        }
    }

    private String visualizarJogos() throws FileNotFoundException, IOException
    {
        String linha = null;
        String jogos = null;
        BufferedReader leitor = lerArquivo();
        jogos = leitor.readLine();
        jogos = jogos + "          " + leitor.readLine();
        while ((linha = leitor.readLine()) != null)
        {
            jogos = jogos + "\n" + linha + "          " + leitor.readLine();
        }
        return jogos + "\n";
    }

    private BufferedReader lerArquivo() throws FileNotFoundException
    {
        File arquivo;
        //arquivo = new File(getClass().getResource("/resources/lotofacil.txt").toURI());
        arquivo = new File("lotofacil.txt");
        FileReader reader = new FileReader(arquivo);
        BufferedReader leitor = new BufferedReader(reader);
        return leitor;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConferir;
    private javax.swing.JButton buttonMaisJogados;
    private javax.swing.JButton buttonVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logotipo;
    private javax.swing.JComboBox n1;
    private javax.swing.JComboBox n10;
    private javax.swing.JComboBox n11;
    private javax.swing.JComboBox n12;
    private javax.swing.JComboBox n13;
    private javax.swing.JComboBox n14;
    private javax.swing.JComboBox n15;
    private javax.swing.JComboBox n2;
    private javax.swing.JComboBox n3;
    private javax.swing.JComboBox n4;
    private javax.swing.JComboBox n5;
    private javax.swing.JComboBox n6;
    private javax.swing.JComboBox n7;
    private javax.swing.JComboBox n8;
    private javax.swing.JComboBox n9;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painelNumeros;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
